server:
  port:8080
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    password: sa
    username: sa
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
